/*
 * generated by Xtext
 */
package raven.ui.contentassist

import raven.ui.contentassist.AbstractSQFProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SQFProposalProvider extends AbstractSQFProposalProvider {
}
