/*
 * generated by Xtext
 */
package raven;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SQFRuntimeModule extends raven.AbstractSQFRuntimeModule {

}
