/*
 * generated by Xtext
 */
package raven.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import raven.services.SQFGrammarAccess;

public class SQFParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SQFGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected raven.parser.antlr.internal.InternalSQFParser createParser(XtextTokenStream stream) {
		return new raven.parser.antlr.internal.InternalSQFParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public SQFGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SQFGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
